version: "3"

tasks:
    migrtest:
      aliases:
        - go
      desc: ""
      cmds:
        - go run E:/prim/GRPC_Server/sso/cmd/migrator --storage-path=E:/prim/GRPC_Server/sso/storage/sso.db --migrations-path=E:/prim/GRPC_Server/sso/tests/migrations --migrations-table=migrations_test
